services:
  notes_api:
    image: ${DOCKER_REGISTRY_}notes_api
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - notes_db
    networks:
      mynotes_net:
        
  notes_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - notes_data:/var/opt/mssql
    networks:
      mynotes_net:
    restart: unless-stopped
  
volumes:
  notes_data:
    
networks:
  mynotes_net:
    driver: bridge
